### ISSUE TITLE
Can't Login and Auto Checkout not working

### ISSUE THREAD

**Issue by chavab1** [ericmartel/Sublime-Text-3-Perforce-Plugin#21]
I know these issues have been reported before but most of them are at least 3 years old so I figured maybe my problem isn't related. I'm also getting an error that hasn't been reported.

First off I did all of the command line configurations. I had to set the required variables on the command line because no matter what I did I couldn't get P4 to recognize my configurations in my P4CONFIG. But I know they're set because I get the correct info when I run `p4 info`.

When I try to login to P4 on Sublime I get the following error in the console: 

```

Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\Perforce\Perforce.py", line 995, in on_done
    p = subprocess.Popen(command, stdin=subprocess.PIPE,stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=global_folder, shell=True)            
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
```

But then I realized that if I'm logged in to P4V then I don't get that error in Sublime when I attempt to login. Everything works then except for the `auto checkout` feature. I did some research and found out that I had to add the Perforce settings file. So I copied Perforce.sublime-settings file from the Perforce directory into my Sublime Text 3->Packages->User directory. But I still have the same problem.  I'm thinking maybe that login problem is causing the auto checkout problem. 

I wouldn't mind having to login to P4V before using Sublime as long as the auto-checkout feature worked.

Any help would be appreciated.

Thanx

**Comment by ericmartel** [comment]
Hi!

As you can tell, I haven't actively worked on this in ages

From your error message, I suspect your p4 executable isn't accessible from the command line.  Can you try to open a command prompt and run p4.exe and see if it is found?

Thanks

Eric

**Comment by chavab1** [comment]
Hi Eric,
Thank you very much for your quick reply and for a great tool.
Yeah, when I run p4.exe on my command prompt it does find it. I get the Perforce greeting screen.
Any other ideas??
Once again, thanx!!

**Comment by ericmartel** [comment]
Well it seems like the plugin is calling something from the command line
and can't find it... did you specify something as your perforce_p4path or
perforce_p4env?  This seems to be the variables that could change what's
being called on your system.

**Comment by chavab1** [comment]
Sorry, I didn't notice you had replied.

What do I have to include there?

For "perforce_p4path" I added `C:\\Program Files\\Perforce`.
What do I have to include in "perforce_p4env"? I tried following the directions on this [thread](https://github.com/ericmartel/Sublime-Text-3-Perforce-Plugin/issues/13) but I was unsuccessful. When I added the path to my P4CONFIG file I would get `file is not under client root` whenever I tried to manually checkout a file.

I mean now at least I don't get the login error message anymore but I still can't auto checkout items. I can manually check out some files. However I can only do it for random files. On some of them I get the message: `Perfoce [warning]: File is already writeable`. So I would assume the configuration is kind of working since it can communicate with my workspace. I was just hoping it could check out files automatically or at least if I have to do it manually it could work on all of them.

Thank you very much for your help.

Thanx

**Comment by chavab1** [comment]
I posted about the plugin only working at random times. I just found out when does it work.

For some reason it only auto checks out files that I haven't previously checked out. In those cases the plugin works perfectly. However, once I've checked in that file and done a submit, the auto checkout stops working on that file.

I'm fairly new to Perforce so I'm not sure where to look for a possible solution. Obviously Sublime is communicating with Perforce so the setup is correct. I just can't figure out why it only works on new files.

Any help would be appreciated.

Thanx

**Comment by ericmartel** [comment]
Oh my bad it seems like it's me who missed your reply!

Are you sure it's working to checkout files on the first edit?  or would it
be only "mark for add" that's working with new files?

Otherwise what would usually trigger the autocheckout is if you modify a
file that is readonly on disk but is under the client root (p4 info on the
command prompt)

I haven't used my own scripts in quite a while, I'll try getting the latest
version at work tomorrow and see if I broke something by accepting pull
requests

Thanks

**Comment by chavab1** [comment]
No, it is checking them out. It also does the same thing if I do it manually. I'll open up the Perforce menu item within Sublime, select Checkout and it works. But only if I haven't already previously checked out and submitted that file. Otherwise I get the error message: Perforce [warning]: File is already writeable.

Thanx for looking into this.

**Comment by ericmartel** [comment]
After a check in, are the files on your hard drive set back to Read Only?

**Comment by chavab1** [comment]
No they are not. I checked the properties in File Explorer and it's neither Read-Only nor Hidden. Is this what you're talking about?? Or is there another way to confirm?? I tried looking for file properties in the P4V client but I couldn't find anything. Sorry, I'm still fairly new to the Perforce system.
Once again, thanx for your help.
